AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  CertificateARN:
    Type: String
    Default: 'arn:aws:acm:eu-west-1:199686536682:certificate/928c2c31-7338-4506-8914-a27b6f3fc38d'

Resources:
  LoadBalancerSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: "xtdb-cloud-public-load-balancer"
      GroupDescription: "Access to the public-facing load balancer"
      VpcId: !ImportValue 'xtdb-vpc:VPC'
      SecurityGroupIngress:
        # Allow access to ALB from anywhere on the internet
        - CidrIp: 0.0.0.0/0
          IpProtocol: -1

  LoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Scheme: internet-facing
      LoadBalancerAttributes:
      - Key: idle_timeout.timeout_seconds
        Value: '30'
      Subnets:
        - !ImportValue 'xtdb-vpc:PublicSubnetOne'
        - !ImportValue 'xtdb-vpc:PublicSubnetTwo'
      SecurityGroups: [!Ref 'LoadBalancerSG']

  LoadBalancerHTTPListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn: !Ref 'LoadBalancer'
      Port: 80
      Protocol: HTTP
      DefaultActions:
        - Type: 'redirect'
          RedirectConfig:
            Port: 443
            Protocol: HTTPS
            StatusCode: HTTP_302

  LoadBalancerHTTPSListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn: !Ref 'LoadBalancer'
      Port: 443
      Protocol: HTTPS
      Certificates:
         - CertificateArn: !Ref CertificateARN
      DefaultActions:
        - Type: 'fixed-response'
          FixedResponseConfig:
            StatusCode: 503

Outputs:
  LoadBalancerSG:
    Value: !Ref 'LoadBalancerSG'

  LoadBalancer:
    Value: !Ref 'LoadBalancer'

  LoadBalancerDNSName:
    Value: !GetAtt ['LoadBalancer', 'DNSName']

  LoadBalancerCanonicalHostedZoneId:
    Value: !GetAtt ['LoadBalancer', 'CanonicalHostedZoneID']

  LoadBalancerHTTPSListener:
    Value: !Ref 'LoadBalancerHTTPSListener'
