AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  CurxCloudStack:
    Type: String
    Default: curx-cloud

Resources:
  ConsoleRecordSet:
    Type: AWS::Route53::RecordSet
    Properties:
      AliasTarget:
        DNSName:
          Fn::ImportValue: !Join [':', [!Ref CurxCloudStack, 'LoadBalancerDNSName']]
        EvaluateTargetHealth: false
        HostedZoneId:
          Fn::ImportValue: !Join [':', [!Ref CurxCloudStack, 'LoadBalancerCanonicalHostedZoneId']]
      HostedZoneName: 'xtdb.cloud.'
      Name: 'console.curx.cloud'
      Type: 'A'

  ConsoleTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      HealthCheckIntervalSeconds: 6
      HealthCheckPath: /latest-completed-tx
      HealthCheckProtocol: HTTP
      HealthCheckTimeoutSeconds: 5
      HealthyThresholdCount: 2
      TargetType: ip
      Name: 'curx-console-demo'
      Port: 3000
      Protocol: HTTP
      UnhealthyThresholdCount: 2
      VpcId:
        Fn::ImportValue: !Join [':', [!Ref 'CurxCloudStack', 'VPCId']]
      TargetGroupAttributes:
      - Key: deregistration_delay.timeout_seconds
        Value: '10'

  ECRRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: 'curx-console-demo'

  ECSCluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: 'curx-console-demo'

  FargateContainerSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Access to the Fargate containers
      VpcId:
        Fn::ImportValue: !Join [':', [!Ref 'CurxCloudStack', 'VPCId']]

  EcsSecurityGroupIngressFromPublicALB:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      Description: Ingress from the public ALB
      GroupId: !Ref 'FargateContainerSecurityGroup'
      IpProtocol: -1
      SourceSecurityGroupId:
        Fn::ImportValue: !Join [':', [!Ref 'CurxCloudStack', 'LoadBalancerSG']]

  ECSTaskExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        - Effect: Allow
          Principal:
            Service: [ecs-tasks.amazonaws.com]
          Action: ['sts:AssumeRole']
      Path: /
      Policies:
        - PolicyName: AmazonECSTaskExecutionRolePolicy
          PolicyDocument:
            Statement:
            - Effect: Allow
              Action:
                # Allow the ECS Tasks to download images from ECR
                - 'ecr:GetAuthorizationToken'
                - 'ecr:BatchCheckLayerAvailability'
                - 'ecr:GetDownloadUrlForLayer'
                - 'ecr:BatchGetImage'
              Resource: '*'

  ConsoleTaskDef:
    Type: AWS::ECS::TaskDefinition
    DependsOn:
      - ECSCluster
      - ECSTaskExecutionRole
    Properties:
      Cpu: '0.5 vCPU'
      Memory: '2GB'
      Family: 'curx-console-demo'
      ExecutionRoleArn:
        Fn::GetAtt: ["ECSTaskExecutionRole", "Arn"]
      RequiresCompatibilities:
        - 'FARGATE'
      NetworkMode: 'awsvpc'
      ContainerDefinitions:
        - Name: 'curx-console-demo'
          Image: '955308952094.dkr.ecr.eu-west-1.amazonaws.com/curx-console-demo:latest'
          PortMappings:
            - ContainerPort: 3000

  LBListenerRule:
    Type: AWS::ElasticLoadBalancingV2::ListenerRule
    Properties:
      Actions:
        - Type: forward
          TargetGroupArn: !Ref ConsoleTargetGroup
      Conditions:
        - Field: host-header
          Values:
            - 'console.curx.cloud'
      ListenerArn:
        Fn::ImportValue: !Join [':', [!Ref 'CurxCloudStack', 'LoadBalancerHTTPSListener']]
      Priority: 20

  Service:
    Type: AWS::ECS::Service
    DependsOn:
      - ConsoleTaskDef
    Properties:
      ServiceName: 'curx-console-demo'
      Cluster: 'curx-console-demo'
      LaunchType: FARGATE
      HealthCheckGracePeriodSeconds: 600
      DeploymentConfiguration:
        MaximumPercent: 200
        MinimumHealthyPercent: 75
      DesiredCount: 0
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: 'ENABLED'
          SecurityGroups:
            - !Ref 'FargateContainerSecurityGroup'
          Subnets:
            - Fn::ImportValue:
                !Join [':', [!Ref 'CurxCloudStack', 'PublicSubnetOne']]
            - Fn::ImportValue:
                !Join [':', [!Ref 'CurxCloudStack', 'PublicSubnetTwo']]
      TaskDefinition: !Ref 'ConsoleTaskDef'
      LoadBalancers:
        - ContainerName: 'curx-console-demo'
          ContainerPort: 3000
          TargetGroupArn: !Ref 'ConsoleTargetGroup'
